---
namespace: nephelaiio
name: rke
version: 0.0.31
readme: README.md
authors:
  - Ted Cook <358176+teddyphreak@users.noreply.github.com>
description: RKE collection
license:
  - MIT
tags:
  - k8s
  - rke
dependencies:
  "nephelaiio.plugins": "*"
  "nephelaiio.consul": "*"
repository: http://github.com/nephelaiio/ansible-collection-rke
documentation: http://github.com/nephelaiio/ansible-collection-rke
homepage: http://github.com/nephelaiio/ansible-collection-rke
issues: http://github.com/nephelaiio/ansible-collection-rke/issues
build_ignore: []
