---
roles: []
collections:
  - name: nephelaiio.rke
    source: .
    type: dir
  - name: nephelaiio.plugins
  - name: nephelaiio.consul
  - name: nephelaiio.libvirt
  - name: community.molecule
  - name: ansible.utils
