---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: rke-install-control01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_control
      - rke
  - name: rke-install-control02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_control
      - rke
  - name: rke-install-control03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_control
      - rke
  - name: rke-install-worker01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_worker
      - rke
  - name: rke-install-worker02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_worker
      - rke
  - name: rke-install-worker03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_worker
      - rke
provisioner:
  name: ansible
  playbooks:
    create: ../common/create.yml
    prepare: ../common/prepare.yml
    converge: ../common/install.yml
    destroy: ../common/destroy.yml
    side_effect: ../common/install.yml
    verify: ../common/verify.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
