---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: rke-api-control01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_control
      - rke
  - name: rke-api-control02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_control
      - rke
  - name: rke-api-control03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_control
      - rke
  - name: rke-api-worker01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_worker
      - rke
  - name: rke-api-worker02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_worker
      - rke
  - name: rke-api-worker03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_worker
      - rke
provisioner:
  name: ansible
  playbooks:
    create: ../common/create.yml
    prepare: ../common/prepare.yml
    converge: ../common/install.yml
    cleanup: ../common/cleanup.yml
    destroy: ../common/destroy.yml
    side_effect: ../common/install.yml
    verify: ../common/verify.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    hosts:
      all:
        vars:
          molecule_libvirt_address: '172.31.254.1/24'
          molecule_libvirt_prefix: "{{ molecule_libvirt_address | ansible.utils.ipaddr('prefix') }}"
          molecule_rke_prefix: "{{ (molecule_libvirt_prefix | int) + 1 }}"
          molecule_dhcp: "{{ molecule_libvirt_address | ansible.utils.ipsubnet(molecule_rke_prefix, 0) }}"
          molecule_metallb: "{{ molecule_libvirt_address | ansible.utils.ipsubnet(molecule_rke_prefix, 1) }}"
          molecule_libvirt_dhcp: "{{ molecule_dhcp }}"
          rke_cluster_name: rke.nephelaiio.io
          rke_ssh_key: "/tmp/id_rsa"
          rke_api_url: "https://api.{{ rke_cluster_name }}:6443"
verifier:
  name: ansible
scenario:
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - side_effect
    - verify
