---
# Defaults
rke_defaults_url_api: "https://api.{{ rke_cluster_name }}"
rke_defaults_release_rke: "v1.4.11"
rke_defaults_release_k8s: "v1.24.17-rancher1-1"
rke_defaults_release_docker: "20.10.24"

# Overridable values
_rke_api_url: "{{ rke_api_url | default(rke_defaults_url_api) }}"
_rke_release_rke: "{{ rke_release_rke | default(rke_defaults_release_rke) }}"
_rke_release_k8s: "{{ rke_release_k8s | default(rke_defaults_release_k8s) }}"
_rke_release_docker: "{{ rke_release_docker | default(rke_defaults_release_docker) }}"

# Hardcoded values
rke_install_user: "{{ ansible_user_id }}"
rke_install_root: /opt/rke
rke_state_file: "{{ rke_install_root }}/cluster.rkestate"
rke_bin_rke: /usr/local/bin/rke
rke_bin_helm: /usr/local/bin/helm
rke_ssh_key: ~/.ssh/id_rsa
rke_docker_packages:
  - docker-ce
  - docker-ce-cli
rke_k8s_helm_bin: /usr/local/bin/helm
