---
rke_api_url: "https://api.{{ rke_cluster_name }}"

rke_release_rke: v1.5.0
rke_release_k8s: v1.25.14
rke_release_consul: v1.17.0

rke_install_user: "{{ ansible_user_id }}"
rke_install_root: /opt/rke

rke_ssh_key: ~/.ssh/id_rsa

rke_bin_rke: /usr/local/bin/rke
rke_bin_helm: /usr/local/bin/helm
