- name: Spawn KVM guests
  hosts: localhost
  become: true
  tasks:
    - name: Cache installer iso
      ansible.builtin.get_url:
        url: "{{ iso_installer.url }}"
        dest: "{{ iso_installer.dest | urlsplit('path') }}"

    - name: Destroy KVM guest
      community.libvirt.virt:
        state: destroyed
        name: "{{ guest.installer_hostname }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"
      failed_when: false

    - name: Undefine KVM guest
      community.libvirt.virt:
        command: undefine
        name: "{{ guest.installer_hostname }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"
      failed_when: false

    - name: Destroy KVM guest disks
      ansible.builtin.file:
        path: "{{ guest_disk }}"
        state: absent
      vars:
        guest_disk: "{{ cache_dir }}/{{ guest.installer_hostname }}.img"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"

    - name: Create KVM guest disks
      ansible.builtin.command: "qemu-img create {{ guest_disk }} {{ guest_disk_size }}"
      args:
        creates: "{{ guest_disk }}"
      vars:
        guest_disk: "{{ cache_dir }}/{{ guest.installer_hostname }}.img"
        guest_disk_size: "{{ guest.installer_disk_size }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"
