---
- name: Configure KVM networking
  hosts: localhost
  become: true
  tasks:
    - name: Stop KVM guests
      community.libvirt.virt:
        name: "{{ item.name }}"
        state: shutdown
      loop_control:
        label: "{{ item.name }}"
      loop: "{{ molecule_yml.platforms }}"
      ignore_errors: true

    - name: Undefine KVM guests
      community.libvirt.virt:
        name: "{{ item.name }}"
        state: shutdown
      loop_control:
        label: "{{ item.name }}"
      loop: "{{ molecule_yml.platforms }}"
      ignore_errors: true
