---
- name: Configure KVM networking
  hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Destroy libvirt pool
      community.libvirt.virt_pool:
        state: deleted
        name: "{{ _libvirt_pool }}"

    - name: Query active KVM guests
      ansible.builtin.command: virsh list --name
      register: guest_query

    - name: Stop KVM guests
      ansible.builtin.command: virsh destroy {{ item }}
      loop: "{{ molecule_yml.platforms | selectattr('name', 'in', guest_query.stdout_lines) | map(attribute='name') }}"

    - name: Query defined KVM guests
      ansible.builtin.command: virsh list --name --all
      register: guest_query

    - name: Undefine KVM guests
      ansible.builtin.command: virsh undefine {{ item }}
      loop: "{{ molecule_yml.platforms | selectattr('name', 'in', guest_query.stdout_lines) | map(attribute='name') }}"

    - name: Delete guest disks
      ansible.builtin.file:
        dest: "{{ _path }}"
        state: absent
      vars:
        _extensions: ['img', 'iso']
        _path: "{{ _libvirt_pool }}/{{ item.0 }}.{{ item.1 }}"
      loop_control:
        label: "{{ _path }}"
      loop: "{{ molecule_yml.platforms | map(attribute='name') | product(_extensions) }}"

    - name: Stop libvirt network
      community.libvirt.virt_net:
        command: destroy
        name: "{{ _libvirt_network }}"
      when: _libvirt_network != "default"
      failed_when: false

    - name: Delete libvirt network
      community.libvirt.virt_net:
        command: undefine
        name: "{{ _libvirt_network }}"
      when: _libvirt_network != "default"
