---
- name: Prepare KVM host
  hosts: localhost
  tasks:
    - name: Install KVM requirements
      ansible.builtin.apt:
        name:
          - qemu
          - qemu-kvm
          - qemu-efi
          - libvirt-clients
          - libvirt-daemon-system
          - libvirt-daemon-system-systemd
          - python3-libvirt
      when: ansible_os_family == 'Debian'


- name: Prepare KVM guests
  hosts: all
  become: true
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        package: gpg-agent
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install python3 binary redirection
      ansible.builtin.apt:
        name: python-is-python3
      when: ansible_os_family == 'Debian'
