---
- name: Prepare KVM guests
  hosts: all
  become: true
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        package: gpg-agent
        update_cache: true
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Install python3 binary redirection
      ansible.builtin.apt:
        name: python-is-python3
      when: ansible_os_family == 'Debian'

    - name: Add host entry for rke api
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ rke_api_url | urlsplit('hostname') }}.*"
        line: "{{ ansible_default_ipv4.address }} {{ rke_api_url | urlsplit('hostname') }}"
      when: rke_api_url is defined
