---
- name: Prepare KVM guests
  hosts: all
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        package: gpg-agent
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install python3 binary redirection
      ansible.builtin.apt:
        name: python-is-python3
      when: ansible_os_family == 'Debian'
