---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: rke-${MOLECULE_SCENARIO_NAME}-control-01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_control
      - rke
  - name: rke-${MOLECULE_SCENARIO_NAME}-control-02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_control
      - rke
  - name: rke-${MOLECULE_SCENARIO_NAME}-control-03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_control
      - rke
  - name: rke-${MOLECULE_SCENARIO_NAME}-worker-01
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_worker
      - rke
  - name: rke-${MOLECULE_SCENARIO_NAME}-worker-02
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_worker
      - rke
  - name: rke-${MOLECULE_SCENARIO_NAME}-worker-03
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - rke_worker
      - rke
provisioner:
  name: ansible
  playbooks:
    create: ../common/create.yml
    prepare: ../common/prepare.yml
    converge: ../common/install.yml
    side_effect: ../common/k8s.yml
    verify: ../common/verify.yml
    cleanup: ../common/cleanup.yml
    destroy: ../common/destroy.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    hosts:
      all:
        vars:
          libvirt_address: '172.31.252.1/24'
          libvirt_user: molecule
          libvirt_platforms: "{{ molecule_yml.platforms }}"
          molecule_net_prefix: "{{ libvirt_address | ansible.utils.ipaddr('prefix') }}"
          molecule_metallb_prefix: "{{ (molecule_net_prefix | int) + 1 }}"
          molecule_metallb: "{{ libvirt_address | ansible.utils.ipsubnet(molecule_metallb_prefix, 1) }}"
          molecule_install_dir: "{{ lookup('env', 'MOLECULE_OUTPUT_DIR', default='/tmp/logs') }}"
          molecule_install_log: "{{ molecule_install_dir }}/${MOLECULE_SCENARIO_NAME}"
          k8s_certmanager_issuer_name: local
          # Required k8s params
          rke_cluster_name: rke.nephelaiio.io
          rke_address_pool_private: "{{ molecule_metallb | ansible.utils.ipsubnet(molecule_mlb_prefix, 1)}}"
          rke_metallb_speaker_secret: secret
          # Optional k8s params
          rke_install_user: "{{ libvirt_user }}"
          rke_k8s_opensearch_deploy: false
verifier:
  name: ansible
scenario:
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
