---
- name: Deploy Consul
  hosts: "{{ rke_control | default('rke_control') }}"
  become: true
  any_errors_fatal: true
  tasks:
    - name: Query Consul releases
      community.general.github_release:
        user: hashicorp
        repo: consul
        action: latest_release
        token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') | default(omit) }}"
      register: _consul_release_query
      delegate_to: localhost

    - name: Set Consul facts
      ansible.builtin.set_fact:
        consul_version: "{{ _version | regex_replace('^v', '') }}"
        consul_node_role: "server"
        consul_bootstrap_expect: true
        consul_bootstrap_expect_value: "{{ ansible_play_hosts_all | length }}"
        consul_group_name: "{{ rke_control | default('rke_control') }}"
        consul_datacenter: "{{ rke_cluster_name | regex_replace('[.]', '_') }}"
        consul_encrypt_enable: false
        consul_install_dependencies: false
      vars:
        _version: "{{ rke_consul_version | default(_consul_release_query.tag) }}"

    - name: Deploy Consul
      ansible.builtin.include_role:
        name: nephelaiio.rke.consul
