---
- name: Deploy consul role
  hosts: "{{ rke_control | default('rke_control') }}"
  become: true
  any_errors_fatal: true
  roles:
    - role: hashicorp.consul
      vars:
        consul_node_role: "server"
        consul_bootstrap_expect: true
        consul_bootstrap_expect_value: "{{ ansible_play_hosts_all | length }}"
        consul_group_name: rke_control
        consul_datacenter: "{{ rke_cluster_name }}"
        consul_encrypt_enable: false
  pre_tasks:
    - name: Query helm releases
      community.general.github_release:
        user: hashicorp
        repo: consul
        action: latest_release
      register: _consul_release_query
      delegate_to: localhost

    - name: Set target helm release
      ansible.builtin.set_fact:
        consul_version: "{{ rke_consul_version | default(_consul_release_query.tag) }}"
