---
- name: Install docker
  hosts: "{{ rke | default('rke') }}"
  become: true
  roles:
    - nephelaiio.rke.docker
  vars:
    rke_install_user: "{{ ansible_user_id }}"
    docker_user: "{{ rke_install_user }}"
  pre_tasks:
    - name: Include collection variables
      ansible.builtin.include_vars:
        file: main.yml
  tasks:
    - name: Disable active swap volume
      shell: swapoff -a
      tags: skip_ansible_lint
      become: true

    - name: Disable swap fstab entry
      lineinfile:
        state: absent
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      become: true
