---
- name: Query RKE component versions
  hosts: "{{ rke_localgroup | default('localhost') }}"
  vars_files:
    - main.yml
  tasks:
    - name: Query Helm releases
      community.general.github_release:
        user: helm
        repo: helm
        action: latest_release
        token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') | default(omit) }}"
      register: _helm_release_query

    - name: Set target Helm release
      ansible.builtin.set_fact:
        helm_version: "{{ rke_helm_version | default(_helm_release_query.tag) }}"


- name: Prepare RKE cluster members
  hosts: "{{ rke_control_group }}:{{ rke_localgroup | default('localhost') }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Configure K8s repository
      ansible.builtin.include_role:
        name: nephelaiio.rke.k8s_repo
      vars:
        k8s_repo_release: "{{ _rke_release_k8s }}"

    - name: Install kubectl
      ansible.builtin.package:
        name: kubectl
        state: latest

    - name: Deploy Helm
      ansible.builtin.include_role:
        name: nephelaiio.rke.helm
      vars:
        helm_version: "{{ hostvars['localhost']['helm_version'] }}"
        helm_bin_path: "{{ rke_k8s_helm_bin }}"
