---
- name: Prepare cluster nodes
  ansible.builtin.import_playbook: nephelaiio.rke.prepare

- name: Deploy Helm
  ansible.builtin.import_playbook: nephelaiio.rke.helm

- name: Deploy Docker
  ansible.builtin.import_playbook: nephelaiio.rke.docker

- name: Deploy Consul
  ansible.builtin.import_playbook: nephelaiio.rke.consul

- name: Configure SSH access
  ansible.builtin.import_playbook: nephelaiio.rke.ssh

- name: Deploy RKE cluster
  ansible.builtin.import_playbook: nephelaiio.rke.rke
