---
- name: Prepare cluster nodes
  ansible.builtin.import_playbook: nephelaiio.rke.prepare

- name: Deploy Docker
  ansible.builtin.import_playbook: nephelaiio.rke.docker

- name: Deploy Consul
  ansible.builtin.import_playbook: nephelaiio.rke.consul

- name: Deploy Helm
  ansible.builtin.import_playbook: nephelaiio.rke.helm
