---
- name: Distribute kube_config to control nodes
  hosts: "{{ rke_control | default('rke_control') }}"
  vars:
    _kubeconfig_source: "{{ rke_install_root }}/kube_config_cluster.yml"
    _kubeconfig_target: "~/.kube/config"
  tasks:
    - name: Include collection variables
      ansible.builtin.include_vars:
        file: main.yml

    - name: Create remote kube_config directory
      ansible.builtin.file:
        path: "{{ _kubeconfig_target | dirname }}"
        state: directory
        mode: 0750

    - name: Distribute kube_config file
      block:
        - name: Stat kube_config
          ansible.builtin.stat:
            path: "{{ _kubeconfig_source }}"
          register: _kubeconfig_file
          run_once: true

        - name: Slurp kube_config
          ansible.builtin.slurp:
            src: "{{ _kubeconfig_source }}"
          register: _kubeconfig_slurp
          run_once: true

        - name: Distribute kube_config to all nodes
          ansible.builtin.copy:
            dest: "{{ _kubeconfig_target }}"
            content: "{{ _kubeconfig_content }}"
          vars:
            _kubeconfig_content: "{{ _kubeconfig_slurp['content'] | b64decode }}"
