---
- name: Prepare RKE cluster members
  hosts: "{{ rke_control | default('rke_control') }}:{{ rke_workers | default('rke_workers') }}"
  become: true
  pre_tasks:
    - name: Include collection variables
      ansible.builtin.include_vars:
        file: main.yml

    - name: Install deb ISCSI packages
      ansible.builtin.package:
        name: open-iscsi
      when: ansible_os_family == "Debian"

    - name: Install rpm ISCSI packages
      ansible.builtin.package:
        name: iscsi-initiator-utils
      when: ansible_os_family == "RedHat"

    - name: Add host entries for cluster members
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}.*"
        line: >
          {{ hostvars[item]['ansible_default_ipv4']['address'] }}
          {{ hostvars[item]['ansible_fqdn'] }}
          {{ hostvars[item]['ansible_hostname'] }}
      loop: "{{ ansible_play_hosts }}"
