---
- name: Prepare RKE cluster masters
  hosts: "{{ rke_control_group }}"
  vars_files:
    - main.yml
  tasks:
    - name: Include pip role
      ansible.builtin.include_role:
        name: nephelaiio.rke.pip
        apply:
          become: true


- name: Prepare RKE cluster members
  hosts: "{{ rke_control_group }}:{{ rke_worker_group }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Install deb ISCSI packages
      ansible.builtin.package:
        name: open-iscsi
      when: ansible_os_family == "Debian"

    - name: Install rpm ISCSI packages
      ansible.builtin.package:
        name: iscsi-initiator-utils
      when: ansible_os_family == "RedHat"

    - name: Add host entries for cluster members
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}.*"
        line: "{{ _member_address }} {{ _fqdn }} {{ _hostname }}"
      vars:
        _member_address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        _fqdn: "{{ hostvars[item]['ansible_fqdn'] }}"
        _hostname: "{{ hostvars[item]['ansible_hostname'] }}"
      loop: "{{ ansible_play_hosts }}"
