---
- name: Deploy RKE cluster
  hosts: "{{ rke_control | default('rke_control') }}"
  become: true
  pre_tasks:
    - name: Include collection variables
      ansible.builtin.include_vars:
        file: main.yml
  tasks:
    - name: Create cluster directory structure
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        owner: "{{ rke_install_user }}"
        mode: 0750
      loop:
        - "{{ rke_install_root_dir }}"
        - "{{ rke_install_manifest_dir }}"

    - name: Deploy RKE binary
      ansible.builtin.get_url:
        url: "https://github.com/rancher/rke/releases/download/{{ rke_release_rke }}/rke_linux-amd64"
        dest: "{{ rke_bin_rke }}"
        mode: 0755
