---
- name: Configure cluster SSH access
  hosts: "{{ rke_control_group }}"
  serial: 1
  vars_files:
    - main.yml
  tasks:
    - name: Create SSH directory
      ansible.builtin.file:
        path: "{{ rke_ssh_key | dirname }}"
        state: directory
        mode: 0700

    - name: Create SSH keypair
      community.crypto.openssh_keypair:
        path: "{{ rke_ssh_key }}"
      register: rke_publickey

    - name: Distribute SSH public keys to control nodes
      ansible.posix.authorized_key:
        comment: "{{ item }}"
        user: "{{ _rke_install_user }}"
        key: "{{ rke_publickey.public_key }}"
      loop_control:
        label: "{{ item }}"
      loop: "{{ groups[rke_control_group] }}"
      delegate_to: "{{ item }}"

    - name: Distribute SSH public keys to worker nodes
      ansible.posix.authorized_key:
        comment: "{{ item }}"
        user: "{{ _rke_install_user }}"
        key: "{{ rke_publickey.public_key }}"
      loop_control:
        label: "{{ item }}"
      loop: "{{ groups[rke_worker_group] }}"
      delegate_to: "{{ item }}"
