---
- name: Configure SSH access
  hosts: "{{ rke_control_group }}:{{ rke_worker_group }}"
  vars_files:
    - main.yml
  tasks:
    - name: Create SSH directory
      ansible.builtin.file:
        path: "{{ rke_ssh_key | dirname }}"
        state: directory
        mode: 0700

    - name: Create SSH keypair
      community.crypto.openssh_keypair:
        path: "{{ rke_ssh_key }}"
      register: rke_publickey

    - name: Distribute SSH public keys
      ansible.posix.authorized_key:
        comment: "{{ item }}"
        user: "{{ rke_install_user }}"
        key: "{{ rke_publickey.public_key }}"
      loop_control:
        label: "{{ rke_install_user }}@{{ inventory_hostname }} -> {{ item }}"
      loop: "{{ play_hosts }}"
      delegate_to: "{{ item }}"
