---
name: build
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Build collection
        run: make build
