---
name: k8s

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 5"

jobs:
  molecule:
    name: k8s
    runs-on: libvirt
    strategy:
      matrix:
        scenario:
          - name: k8s
        image:
          - url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: make install

      - name: Debug test environment
        run: make debug

      - name: Install role requirements
        run: make requirements

      - name: Run molecule tests.
        run: make test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_KVM_IMAGE: ${{ matrix.image.url }}
          MOLECULE_SCENARIO: ${{ matrix.scenario.name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
