---
name: versions

on:
  pull_request:
    branches:
      - master

jobs:
  versions:
    name: versions
    runs-on: libvirt
    strategy:
      matrix:
        include:
          - scenario: install
            image: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
            base:
              rke: "v1.4.11"
              k8s: "v1.24.17-rancher1-1"
              docker: "20.10.24"
            target:
              rke: "v1.4.12"
              k8s: "v1.24.17-rancher1-1"
              docker: "20.10.24"
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to pull request target branch
        run: git checkout master

      - name: Debug target ref
        run: git --no-pager log --decorate=short -n1 --pretty=oneline

      - name: Set up python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: make install

      - name: Debug test environment
        run: make debug

      - name: Install role requirements
        run: make requirements

      - name: Converge with target branch
        run: make create prepare converge side-effect
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_KVM_IMAGE: ${{ matrix.image }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RKE_RELEASE_RKE: ${{ matrix.base.rke }}
          RKE_RELEASE_K8S: ${{ matrix.base.k8s }}
          RKE_RELEASE_DOCKER: ${{ matrix.base.docker }}

      - name: Switch to pull request source branch
        run: git checkout ${GIHUB_HEAD_REF}

      - name: Debug base ref
        run: git --no-pager log --decorate=short -n1 --pretty=oneline

      - name: Install dependencies
        run: make install

      - name: Install role requirements
        run: make requirements

      - name: Converge with source branch
        run: make converge side-effect verify
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_KVM_IMAGE: ${{ matrix.image }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RKE_RELEASE_RKE: ${{ matrix.target.rke }}
          RKE_RELEASE_K8S: ${{ matrix.target.k8s }}
          RKE_RELEASE_DOCKER: ${{ matrix.target.docker }}
